#!/usr/bin/env node
// NPM wrapper for Django deployment
const { execSync } = require('child_process');
const args = process.argv.slice(2);

if (args[0] === 'run') {
  if (args[1] === 'build') {
    console.log('Redirecting to Django build process...');
    execSync('node package-scripts.js build', { stdio: 'inherit' });
  } else if (args[1] === 'start') {
    console.log('Redirecting to Django start process...');
    execSync('node package-scripts.js start', { stdio: 'inherit' });
  } else if (args[1] === 'dev') {
    execSync('python manage.py runserver 0.0.0.0:5000', { stdio: 'inherit' });
  } else {
    console.log(`Script "${args[1]}" not found`);
    process.exit(1);
  }
} else {
  // Pass through to real npm
  execSync(`/usr/bin/npm ${args.join(' ')}`, { stdio: 'inherit' });
}