# Generated by Django 5.2.4 on 2025-07-30 01:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_category_recipe_difficulty_recipe_is_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_cloned', models.BooleanField(default=False)),
                ('original_recipe_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('ingredients_data', models.JSONField(default=list)),
                ('instructions_data', models.JSONField(default=list)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-revision_number'],
                'unique_together': {('recipe', 'revision_number')},
            },
        ),
    ]
