# Generated by Django 5.2.4 on 2025-07-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppinglist_shoppinglistitem_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=500)),
                ('replacement', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('ingredient', 'Ingredient'), ('instruction', 'Instruction'), ('description', 'Description'), ('general', 'General')], max_length=20)),
                ('example_before', models.CharField(max_length=500)),
                ('example_after', models.CharField(max_length=500)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_from_feedback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-success_count', 'category', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCleaningFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', models.JSONField()),
                ('cleaned_data', models.JSONField()),
                ('user_corrections', models.JSONField(blank=True, null=True)),
                ('feedback_type', models.CharField(choices=[('good', 'Good'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('specific_issues', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_feedback', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
