# Generated by Django 5.2.4 on 2025-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_cleaningrule_recipecleaningfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='recipe_sources',
            field=models.ManyToManyField(blank=True, related_name='shopping_items', to='recipes.recipe'),
        ),
    ]
